export const USERS_COLLECTION = 'users'
export const CHATS_COLLECTION = 'chats'
export const MEMBERS_COLLECTION = 'members'
export const OWNER_ID = 'ownerId'
export const UNTITLED = 'Untitled'
export const CREATED_AT = 'createdAt'
export const MEMBER_IDS = 'memberIds'
